/**
 * @file        rexglue/commands/upgrade_detect.h
 * @brief       Detect SDK-managed files that need overwriting on codegen upgrade
 *
 * @copyright   Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 *              All rights reserved.
 *
 * @license     BSD 3-Clause License
 *              See LICENSE file in the project root for full license text.
 */

#pragma once

#include <filesystem>
#include <string>
#include <string_view>
#include <vector>

namespace rexglue::cli {

enum class OverwriteAction {
  Write,   ///< Create or overwrite `path` with `rendered_content`.
  Delete,  ///< Remove `path` from disk; `rendered_content` is unused.
};

struct OverwriteEntry {
  std::filesystem::path path;
  std::string rendered_content;
  OverwriteAction action = OverwriteAction::Write;
  /**
   * True when `path` lives inside the project's `generated/` tree, in which
   * case the upgrade flow applies the entry without prompting. False entries
   * require explicit consent (TTY prompt or --force).
   */
  bool silent = false;
  /**
   * Short human-readable explanation of why this entry exists, printed beside
   * the path in the consent prompt. Empty for silent entries.
   */
  std::string reason;
};

/**
 * Detects SDK-managed files that have drifted from their template and produces
 * an overwrite plan. Entries inside the project's `generated/` tree are marked
 * silent; entries outside require user consent before being applied.
 */
class UpgradeDetect {
 public:
  UpgradeDetect();

  /**
   * Build the overwrite plan for the project rooted at `project_root`.
   * Compares each SDK-managed template's freshly-rendered content against
   * the file on disk; entries that differ (or are missing) are returned.
   * `entrypoint_out_dir` is the manifest's [entrypoint].out_directory_path,
   * embedded into rexglue.cmake so it picks up the right sources/dll_targets.
   */
  std::vector<OverwriteEntry> Plan(const std::filesystem::path& project_root,
                                   std::string_view project_name, std::string_view sdk_version,
                                   std::string_view entrypoint_out_dir);

  /**
   * Render the init/rexglue_cmake template fresh. Exposed so tests can
   * produce content that matches Plan()'s expected on-disk version.
   */
  std::string RenderRexglueCmake(std::string_view project_name, std::string_view sdk_version,
                                 std::string_view entrypoint_out_dir);

  /**
   * Walk hand-edited CMake files (CMakeLists.txt and *.cmake) under
   * `project_root` and produce rewrite entries for any literal references to
   * `legacy_config_filename`, replacing them with `manifest_filename`. Files
   * inside `generated/` are skipped; those are regenerated wholesale by
   * other plan entries.
   */
  std::vector<OverwriteEntry> ScanCmakeReferences(const std::filesystem::path& project_root,
                                                  std::string_view legacy_config_filename,
                                                  std::string_view manifest_filename);

  /**
   * Walk source files under `project_root` and produce rewrite entries that
   * migrate `#include "...<project>_config.h"` to `<project>_init.h`. When a
   * file already includes the `_init.h` form, the stale `_config.h` line is
   * dropped instead of duplicating the include. Files inside `generated/`
   * are skipped (regenerated by codegen). Entries are non-silent: edits to
   * hand-written source require explicit consent.
   */
  std::vector<OverwriteEntry> ScanSourceIncludeRewrites(const std::filesystem::path& project_root,
                                                        std::string_view project_name);
};

}  // namespace rexglue::cli
