/**
 * @file        rexglue/commands/upgrade_prompt.cpp
 * @brief       TTY-aware consent prompt for codegen upgrade
 *
 * @copyright   Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 *              All rights reserved.
 *
 * @license     BSD 3-Clause License
 *              See LICENSE file in the project root for full license text.
 */

#include "upgrade_prompt.h"

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <iostream>
#include <string>

#include <fmt/format.h>

#ifdef _WIN32
#include <io.h>
#define rexglue_isatty(fd) _isatty(fd)
#define rexglue_fileno(stream) _fileno(stream)
#else
#include <unistd.h>
#define rexglue_isatty(fd) isatty(fd)
#define rexglue_fileno(stream) fileno(stream)
#endif

namespace rexglue::cli {

namespace {

const char* ActionLabel(OverwriteAction action) {
  switch (action) {
    case OverwriteAction::Write:
      return "write ";
    case OverwriteAction::Delete:
      return "delete";
  }
  return "?     ";
}

void PrintPlan(const std::vector<OverwriteEntry>& plan, std::string_view from_version,
               std::string_view to_version) {
  std::cerr << fmt::format("ReXGlue: project last generated by SDK {}; current SDK is {}\n\n",
                           from_version.empty() ? "(unstamped)" : from_version, to_version);
  std::cerr << "The upgrade will modify the following file(s) outside generated/:\n";
  static constexpr std::string_view kReasonIndent = "           ";
  for (const auto& e : plan) {
    std::cerr << "  [" << ActionLabel(e.action) << "] " << e.path.generic_string() << "\n";
    if (e.reason.empty())
      continue;
    std::cerr << kReasonIndent;
    for (char c : e.reason) {
      std::cerr << c;
      if (c == '\n')
        std::cerr << kReasonIndent;
    }
    std::cerr << "\n";
  }
  std::cerr << "\n";
}

bool StdinIsTty() {
  return rexglue_isatty(rexglue_fileno(stdin)) != 0;
}

bool ReadConsent() {
  std::cerr << "Continue? [y/N] " << std::flush;
  std::string line;
  if (!std::getline(std::cin, line))
    return false;
  std::transform(line.begin(), line.end(), line.begin(),
                 [](unsigned char c) { return std::tolower(c); });
  auto first = line.find_first_not_of(" \t\r\n");
  if (first == std::string::npos)
    return false;
  auto last = line.find_last_not_of(" \t\r\n");
  std::string trimmed = line.substr(first, last - first + 1);
  return trimmed == "y" || trimmed == "yes";
}

}  // namespace

rex::Result<UpgradeConsent> PromptForUpgradeConsent(const std::vector<OverwriteEntry>& plan,
                                                    std::string_view from_version,
                                                    std::string_view to_version, bool force) {
  if (force) {
    return rex::Ok(UpgradeConsent::Granted);
  }

  PrintPlan(plan, from_version, to_version);

  if (!StdinIsTty()) {
    return rex::Err<UpgradeConsent>(
        rex::ErrorCategory::Config,
        fmt::format("Upgrade required for this project ({} -> {}). Re-run with --force to consent.",
                    from_version.empty() ? "(unstamped)" : from_version, to_version));
  }

  return rex::Ok(ReadConsent() ? UpgradeConsent::Granted : UpgradeConsent::Declined);
}

}  // namespace rexglue::cli
